#!/usr/bin/env python3
"""Generate the GitHub Pages root index.html listing all daily demos.

Reads the `daily/` dir from the (main) checkout. For each `YYYY-MM-DD` folder it
detects whether a demo exists (daily/<date>/demo/package.json) and reads
status.json for the opportunity name and status. Demo days link to ./<date>/;
non-demo days are listed as "机会观察（无 Demo）".

Usage:
  python3 scripts/build_pages_index.py --daily daily --out public-site/index.html
"""

from __future__ import annotations

import argparse
import html
import json
import re
from pathlib import Path

DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _load_status(day_dir: Path) -> dict:
    p = day_dir / "status.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def _collect(daily: Path) -> list[dict]:
    rows: list[dict] = []
    if not daily.is_dir():
        return rows
    for d in sorted((p for p in daily.iterdir() if p.is_dir() and DATE_RE.match(p.name)),
                    key=lambda p: p.name, reverse=True):
        st = _load_status(d)
        has_demo = (d / "demo" / "package.json").exists()
        opp = (st.get("opportunity") or {}).get("selected") or ""
        rows.append({
            "date": d.name,
            "has_demo": has_demo,
            "status": st.get("status", "?"),
            "opportunity": opp,
        })
    return rows


def _render(rows: list[dict]) -> str:
    cards = []
    for r in rows:
        date = html.escape(r["date"])
        opp = html.escape(r["opportunity"]) or "—"
        status = html.escape(str(r["status"]))
        if r["has_demo"]:
            link_open = f'<a class="card" href="./{date}/">'
            badge = '<span class="tag live">Demo 可体验</span>'
            action = '<span class="go">打开 Demo →</span>'
        else:
            link_open = '<div class="card nodemo">'
            badge = '<span class="tag partial">机会观察 · 无 Demo</span>'
            action = '<span class="go muted">仅分析</span>'
        link_close = "</a>" if r["has_demo"] else "</div>"
        cards.append(f"""{link_open}
      <div class="row"><span class="date">{date}</span>{badge}</div>
      <div class="opp">{opp}</div>
      <div class="row"><span class="status">status: {status}</span>{action}</div>
    {link_close}""")
    cards_html = "\n    ".join(cards) if cards else '<p class="empty">还没有产物。</p>'

    return f"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Product Opportunity Lab · Daily Demos</title>
<style>
  :root {{ color-scheme: dark; }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"PingFang SC","Microsoft YaHei",sans-serif;
    background:#0b0e14; color:#e6e9ef; }}
  .wrap {{ max-width:920px; margin:0 auto; padding:56px 20px 80px; }}
  h1 {{ font-size:28px; margin:0 0 6px; }}
  .sub {{ color:#8b93a7; margin:0 0 32px; line-height:1.6; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(260px,1fr)); gap:16px; }}
  .card {{ display:block; text-decoration:none; color:inherit; background:#141924; border:1px solid #222a39;
    border-radius:14px; padding:18px; transition:.15s; }}
  a.card:hover {{ border-color:#3b82f6; transform:translateY(-2px); }}
  .card.nodemo {{ opacity:.7; }}
  .row {{ display:flex; align-items:center; justify-content:space-between; gap:8px; }}
  .date {{ font-weight:600; font-size:16px; }}
  .opp {{ color:#c3cad9; font-size:14px; margin:10px 0 14px; line-height:1.5; min-height:38px; }}
  .tag {{ font-size:11px; padding:3px 8px; border-radius:999px; white-space:nowrap; }}
  .tag.live {{ background:#0f2a1a; color:#4ade80; border:1px solid #1f5133; }}
  .tag.partial {{ background:#2a230f; color:#fbbf24; border:1px solid #514a1f; }}
  .status {{ color:#8b93a7; font-size:12px; }}
  .go {{ color:#3b82f6; font-size:13px; }}
  .go.muted {{ color:#8b93a7; }}
  .empty {{ color:#8b93a7; }}
  footer {{ margin-top:40px; color:#6b7280; font-size:13px; }}
  a.src {{ color:#3b82f6; }}
</style>
</head>
<body>
  <div class="wrap">
    <h1>Product Opportunity Lab</h1>
    <p class="sub">每天基于 Product Hunt 新品报告，以连续 AI 创业者视角提出一个创新产品机会，并自动生成可体验的轻量 Demo。<br/>
      源码：<a class="src" href="https://github.com/TOTOROLnet/product-opportunity-lab">TOTOROLnet/product-opportunity-lab</a></p>
    <div class="grid">
    {cards_html}
    </div>
    <footer>Generated by build_pages_index.py</footer>
  </div>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Pages root index.html")
    parser.add_argument("--daily", default="daily")
    parser.add_argument("--out", default="public-site/index.html")
    args = parser.parse_args()

    rows = _collect(Path(args.daily))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_render(rows), encoding="utf-8")
    print(f"[pages-index] wrote {out} with {len(rows)} day(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
